platform :ios, '13.2'

target 'PR-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PR-App

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

# https://firebase.google.com/docs/ios/setup#available-pods

  target 'PR-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PR-AppUITests' do
    # Pods for testing
  end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end

end
