platform :ios, '13.2'

target 'PR-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PR-App

pod 'Firebase/Analytics'
pod 'Firebase/Auth'

# https://firebase.google.com/docs/ios/setup#available-pods

  target 'PR-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PR-AppUITests' do
    # Pods for testing
  end

end
